### ISSUE TITLE
Inconsistent typedef rules

### ISSUE THREAD

**Issue by EdJoPaTo** [xojs/tslint-xo#14]
#13 introduced multiple inconsistencies for me (examples seen below). It is not possible to create code that has no lint errors. (Or maybe I am doing something wrong?)

As @sindresorhus already [pointed out](https://github.com/xojs/tslint-xo/pull/13#issuecomment-457824148) `variable-declaration` was annoying this clearly has been used and I am not sure why the problems I am pointing out were not found / removed? Do I miss something obvious?

As a fix I would remove the typedef requirement for the ones I pointed out below. Or maybe there is a better solution?

Because of this I checked the other typedef requirements and think they are still useful:
* `call-signature`
* `arrow-call-signature`
* `property-declaration`
* `member-variable-declaration`

# Examples

## `arrow-parameter` 
```ts
import test, {ExecutionContext} from 'ava';

test('1', t => {
	t.pass();
});

test('2', (t: ExecutionContext) => {
	t.pass();
});
```

error messages:
```
ERROR: 3:11   typedef                         expected arrow-parameter: 't' to have a typedef
ERROR: 7:13   no-unnecessary-type-annotation  type annotation is redundant
```

## `parameter`
```ts
function meh(foo: string = 'bar', bar = 'foo'): string {
	return foo + bar;
}
```

error messages:
```
ERROR: 1:19   no-inferrable-types             Type string trivially inferred from a string literal, remove type annotation
ERROR: 1:35   typedef                         expected parameter: 'bar' to have a typedef
```

## `object-destructuring`
```ts
const testObj = {paramA: 'test', paramB: 15};

function caseA(): string {
	const {paramA, paramB} = testObj;
	return paramA + String(paramB);
}

function caseB(): string {
	const {paramA, paramB}: {paramA: string; paramB: number; } = testObj;
	return paramA + String(paramB);
}
```

error messages:
```
ERROR: 4:8    typedef                         expected object-destructuring: '{paramA, paramB}' to have a typedef
ERROR: 9:24   no-unnecessary-type-annotation  type annotation is redundant
```

## `array-destructuring`
```ts
const testArr = [1, 2, 3];

function caseA(): number {
	const [first, second, third] = testArr;
	return first + second + third;
}

function caseB(): number {
	const [first, second, third]: number[] = testArr;
	return first + second + third;
}
```

error messages:
```
ERROR: 4:8    typedef                         expected array-destructuring: '[first, second, third]' to have a typedef
ERROR: 9:30   no-unnecessary-type-annotation  type annotation is redundant
```

**Comment by bartcallant** [comment]
I'm having a similar issue when using the `map` operator on an array:

```typescript
['foo'].map((s: string, i: number): string => `${i}${s.toUpperCase()}`);
```

Errors:
```
ERROR: 1:26  no-unnecessary-type-annotation  type annotation is redundant
```

Errors when removing the type for `s` and `i`:
```
ERROR: 1:14  typedef                         expected arrow-parameter: 's' to have a typedef
ERROR: 1:17  typedef                         expected arrow-parameter: 'i' to have a typedef
```

**Comment by sindresorhus** [comment]
Sorry for the inconvenience. I should have tested this better. I didn't hit this in one project as TSLint was not working correctly and in the other project I used for dogfooding this, it was so many errors for `typedef` that I disabled it until I would have a chance to go through it.

**Comment by sindresorhus** [comment]
> arrow-parameter

I think it would be nice to be explicit about parameter types here, but I tihnk the rule needs an option to not have to type functions in arrow parameters (callbacks).

> parameter

I think the `typedef` rule should have an option to not require types for parameters with default argument literals.

**Comment by sindresorhus** [comment]
I really think these two rules should have been one rule with various options to customize it. Please open issues on TSLint if you agree.

**Comment by EdJoPaTo** [comment]
I read through a bunch of issues for TSLint regarding `typedef` (why haven't I done this earlier?) and in most cases the TS compiler option `noImplicitAny` does this job already perfectly fine.

I tried all of the above code and did not get any false positives while having errors with `tsc` for correctly detected missing types. 👍

This may break some builds but as you are requiring lint and build to work I don't think it's worse than having a lint error.

`--noImplicitAny  Raise error on expressions and declarations with an implied 'any' type.`
