### ISSUE TITLE
Import should be named '.' but found 'm'

### ISSUE THREAD

**Issue by SamVerschueren** [xojs/tslint-xo#2]
I get an error when I import a default export, for instance in my tests.

```ts
import m from '..';
```

> [tslint] Misnamed import. Import should be named '.' but found 'm' (import-name)

**Comment by sindresorhus** [comment]
See: https://github.com/Microsoft/tslint-microsoft-contrib/issues/378 I'll just disable the rule.

**Comment by SamVerschueren** [comment]
Thanks!
