### ISSUE TITLE
Should we disable `early-exit`?

### ISSUE THREAD

**Issue by SamVerschueren** [xojs/tslint-xo#5]
I'm not sure about the [early-exit](https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/early-exit.md) rule to be honest. Most of the time, it enforces me to rewrite my if-statements. I just want to discuss if other people experienced the same issues, maybe it's just me having to get used to the rule :).

For instance. This piece of code fails

```ts
for (const x of xs) {
	if (so) {
		simple;
	} else {
		lots;
		of;
		code;
	}
}
```

It enforces you to rewrite it to

```ts
for (const x of xs) {
	if (so) {
		simple;
		continue;
	}

	lots;
	of;
	code;
}
```

Which I feel to be less readable. For my own use case, I came across the following block.

```ts
ngOnChanges() {
	if (this.meal && this.meal.name) {
		this.exists = true;

		const value = this.meal;
		this.form.patchValue(value);
	}
}
```

This is wrong, because it prefers an early exit.

```ts
ngOnChanges() {
	if (!this.meal || !this.meal.name) {
		return;
	}

	this.exists = true;

	const value = this.meal;
	this.form.patchValue(value);
}
```

I can see the benefit of early exits in some use cases, but not always.

Want to have some other opinions on this one.

// @kevva

**Comment by kevva** [comment]
I actually like the `continue`. This forces you to use the same style everywhere like you do with `break`, `return` and `throw`. It's also easier to spot what's the "main" code of a block if it has a lower indent IMO, but this is all personal preference I guess.

**Comment by crazy4groovy** [comment]
I've found that early-exits make my code much easier to refactor into it's own pieces later on; especially helpful for unit testing purposes. However, using "else" or "nested ifs" makes the code very dependant on its context/conditions, thus harder to refactor. Just my experience.

**Comment by sindresorhus** [comment]
I also find that early-returns make the code more readable in general, although I'm sure that's subjective.
