### ISSUE TITLE
Add support to Definite Assignment Assertions

### ISSUE THREAD

**Issue by NicoCevallos** [xojs/tslint-xo#8]
TS 2.7+ requires property initialization and a way to suppress this requirement, due the property is initialized out of the constructor, is using the Definite Assignment Assertions, but to do that I need to disable the `semicolon` and `whitespace` rules each time I need to do that

I would like to use the Definite Assignment Assertions without any problem.

More info here:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#definite-assignment-assertions

**Comment by sindresorhus** [comment]
> but to do that I need to disable the semicolon and whitespace rules each time I need to do that

It's not clear why you need to do that, but it sounds like those rules needs to be updated to support Definite Assignment Assertions. You might want to open an issue about that here: https://github.com/palantir/tslint
